# This file has been generated by node2nix 1.5.3. Do not edit!

{nodeEnv, fetchurl, fetchgit, globalBuildInputs ? []}:

let
  sources = {
    "commander-2.17.1" = {
      name = "commander";
      packageName = "commander";
      version = "2.17.1";
      src = fetchurl {
        url = "https://registry.npmjs.org/commander/-/commander-2.17.1.tgz";
        sha512 = "21fbnprzkj53pjsp5wd7f5wa50jrirag11gq351jr8hhrib5gw62kylpvcddv3c2a1vcs1p8llq80wdnflh6lny3frnq7v7l6vi9wy0";
      };
    };
    "source-map-0.6.1" = {
      name = "source-map";
      packageName = "source-map";
      version = "0.6.1";
      src = fetchurl {
        url = "https://registry.npmjs.org/source-map/-/source-map-0.6.1.tgz";
        sha512 = "3p7hw8p69ikj5mwapmqkacsjnbvdfk5ylyamjg9x5izkl717xvzj0vk3fnmx1n4pf54h5rs7r8ig5kk4jv4ycqqj0hv75cnx6k1lf2j";
      };
    };
  };
in
{
  "uglify-js-3.4.9" = nodeEnv.buildNodePackage {
    name = "uglify-js";
    packageName = "uglify-js";
    version = "3.4.9";
    src = fetchurl {
      url = "https://registry.npmjs.org/uglify-js/-/uglify-js-3.4.9.tgz";
      sha512 = "3axdjl69nv292w1d80vw7pa6rlj14xz4j307268hz2xszfgqf03fswhbf56w4fvkfk5b24c5ag4m9lv7aqyibrwn74vj4ddldn6q8ph";
    };
    dependencies = [
      sources."commander-2.17.1"
      sources."source-map-0.6.1"
    ];
    buildInputs = globalBuildInputs;
    meta = {
      description = "JavaScript parser, mangler/compressor and beautifier toolkit";
      homepage = "https://github.com/mishoo/UglifyJS2#readme";
      license = "BSD-2-Clause";
    };
    production = true;
    bypassCache = true;
  };
}