# This file has been generated by node2nix 1.5.3. Do not edit!

{nodeEnv, fetchurl, fetchgit, globalBuildInputs ? []}:

let
  sources = {
    "ansi-regex-2.1.1" = {
      name = "ansi-regex";
      packageName = "ansi-regex";
      version = "2.1.1";
      src = fetchurl {
        url = "https://registry.npmjs.org/ansi-regex/-/ansi-regex-2.1.1.tgz";
        sha1 = "c3b33ab5ee360d86e0e628f0468ae7ef27d654df";
      };
    };
    "ansi-regex-3.0.0" = {
      name = "ansi-regex";
      packageName = "ansi-regex";
      version = "3.0.0";
      src = fetchurl {
        url = "https://registry.npmjs.org/ansi-regex/-/ansi-regex-3.0.0.tgz";
        sha1 = "ed0317c322064f79466c02966bddb605ab37d998";
      };
    };
    "ansi-styles-2.2.1" = {
      name = "ansi-styles";
      packageName = "ansi-styles";
      version = "2.2.1";
      src = fetchurl {
        url = "https://registry.npmjs.org/ansi-styles/-/ansi-styles-2.2.1.tgz";
        sha1 = "b432dd3358b634cf75e1e4664368240533c1ddbe";
      };
    };
    "ansi-styles-3.2.1" = {
      name = "ansi-styles";
      packageName = "ansi-styles";
      version = "3.2.1";
      src = fetchurl {
        url = "https://registry.npmjs.org/ansi-styles/-/ansi-styles-3.2.1.tgz";
        sha512 = "2lgkskkj4c1fsnrksy0yffda0wss84p8lfiazdc7jli7iqnvrxkzbxjzpvx13lm28qw0zkawfxvz2bdiisc72ccy7hx8i8rm4iijgam";
      };
    };
    "anymatch-1.3.2" = {
      name = "anymatch";
      packageName = "anymatch";
      version = "1.3.2";
      src = fetchurl {
        url = "https://registry.npmjs.org/anymatch/-/anymatch-1.3.2.tgz";
        sha512 = "269dbx666z4ws49vag1dma5kdpjlx83s74c1jlngrn2672rhvbc47i5ay5h40spmrzgvbvcm33i4yrp88rrc6lg70v78k155z45lwyi";
      };
    };
    "argparse-1.0.10" = {
      name = "argparse";
      packageName = "argparse";
      version = "1.0.10";
      src = fetchurl {
        url = "https://registry.npmjs.org/argparse/-/argparse-1.0.10.tgz";
        sha512 = "17fhywmdjcp8g0ys089i5xg26yajkkg9zg8hyry3fghz75b2pq5vdx997dk5p2sc15r9nsj8rmf4f27g81hi92kzj5q86sdmg5ni553";
      };
    };
    "arr-diff-2.0.0" = {
      name = "arr-diff";
      packageName = "arr-diff";
      version = "2.0.0";
      src = fetchurl {
        url = "https://registry.npmjs.org/arr-diff/-/arr-diff-2.0.0.tgz";
        sha1 = "8f3b827f955a8bd669697e4a4256ac3ceae356cf";
      };
    };
    "arr-flatten-1.1.0" = {
      name = "arr-flatten";
      packageName = "arr-flatten";
      version = "1.1.0";
      src = fetchurl {
        url = "https://registry.npmjs.org/arr-flatten/-/arr-flatten-1.1.0.tgz";
        sha512 = "2vdly17xk5kw7bfzajrjdnw4ml3wrfblx8064n0i4fxlchcscx2mvnwkq2bnnqvbqvdy4vs9ad462lz0rid7khysly9m9vzjiblly1g";
      };
    };
    "array-union-1.0.2" = {
      name = "array-union";
      packageName = "array-union";
      version = "1.0.2";
      src = fetchurl {
        url = "https://registry.npmjs.org/array-union/-/array-union-1.0.2.tgz";
        sha1 = "9a34410e4f4e3da23dea375be5be70f24778ec39";
      };
    };
    "array-uniq-1.0.3" = {
      name = "array-uniq";
      packageName = "array-uniq";
      version = "1.0.3";
      src = fetchurl {
        url = "https://registry.npmjs.org/array-uniq/-/array-uniq-1.0.3.tgz";
        sha1 = "af6ac877a25cc7f74e058894753858dfdb24fdb6";
      };
    };
    "array-unique-0.2.1" = {
      name = "array-unique";
      packageName = "array-unique";
      version = "0.2.1";
      src = fetchurl {
        url = "https://registry.npmjs.org/array-unique/-/array-unique-0.2.1.tgz";
        sha1 = "a1d97ccafcbc2625cc70fadceb36a50c58b01a53";
      };
    };
    "async-each-1.0.1" = {
      name = "async-each";
      packageName = "async-each";
      version = "1.0.1";
      src = fetchurl {
        url = "https://registry.npmjs.org/async-each/-/async-each-1.0.1.tgz";
        sha1 = "19d386a1d9edc6e7c1c85d388aedbcc56d33602d";
      };
    };
    "balanced-match-1.0.0" = {
      name = "balanced-match";
      packageName = "balanced-match";
      version = "1.0.0";
      src = fetchurl {
        url = "https://registry.npmjs.org/balanced-match/-/balanced-match-1.0.0.tgz";
        sha1 = "89b4d199ab2bee49de164ea02b89ce462d71b767";
      };
    };
    "binary-extensions-1.11.0" = {
      name = "binary-extensions";
      packageName = "binary-extensions";
      version = "1.11.0";
      src = fetchurl {
        url = "https://registry.npmjs.org/binary-extensions/-/binary-extensions-1.11.0.tgz";
        sha1 = "46aa1751fb6a2f93ee5e689bb1087d4b14c6c205";
      };
    };
    "brace-expansion-1.1.11" = {
      name = "brace-expansion";
      packageName = "brace-expansion";
      version = "1.1.11";
      src = fetchurl {
        url = "https://registry.npmjs.org/brace-expansion/-/brace-expansion-1.1.11.tgz";
        sha512 = "248cnpbbf0p32h53rd3g8wzpgrkaj4p078ra1g6l16f82i6bzkvmhwqan5rk88apbll9ly1476kngd7f7z27i3b3zxpbb3064f8yaw8";
      };
    };
    "braces-1.8.5" = {
      name = "braces";
      packageName = "braces";
      version = "1.8.5";
      src = fetchurl {
        url = "https://registry.npmjs.org/braces/-/braces-1.8.5.tgz";
        sha1 = "ba77962e12dff969d6b76711e914b737857bf6a7";
      };
    };
    "builtin-modules-1.1.1" = {
      name = "builtin-modules";
      packageName = "builtin-modules";
      version = "1.1.1";
      src = fetchurl {
        url = "https://registry.npmjs.org/builtin-modules/-/builtin-modules-1.1.1.tgz";
        sha1 = "270f076c5a72c02f5b65a47df94c5fe3a278892f";
      };
    };
    "camelcase-4.1.0" = {
      name = "camelcase";
      packageName = "camelcase";
      version = "4.1.0";
      src = fetchurl {
        url = "https://registry.npmjs.org/camelcase/-/camelcase-4.1.0.tgz";
        sha1 = "d545635be1e33c542649c69173e5de6acfae34dd";
      };
    };
    "chalk-1.1.3" = {
      name = "chalk";
      packageName = "chalk";
      version = "1.1.3";
      src = fetchurl {
        url = "https://registry.npmjs.org/chalk/-/chalk-1.1.3.tgz";
        sha1 = "a8115c55e4a702fe4d150abd3872822a7e09fc98";
      };
    };
    "chalk-2.4.1" = {
      name = "chalk";
      packageName = "chalk";
      version = "2.4.1";
      src = fetchurl {
        url = "https://registry.npmjs.org/chalk/-/chalk-2.4.1.tgz";
        sha512 = "1yl5ffjp5w65b9ydnw4vp13n563121hs64xbnajif51grhpqmslaqllj24zm1pfaw9ywvdx69n8ppa3riwlps25k5934zgnbf3pmcrr";
      };
    };
    "chokidar-1.7.0" = {
      name = "chokidar";
      packageName = "chokidar";
      version = "1.7.0";
      src = fetchurl {
        url = "https://registry.npmjs.org/chokidar/-/chokidar-1.7.0.tgz";
        sha1 = "798e689778151c8076b4b360e5edd28cda2bb468";
      };
    };
    "cli-cursor-2.1.0" = {
      name = "cli-cursor";
      packageName = "cli-cursor";
      version = "2.1.0";
      src = fetchurl {
        url = "https://registry.npmjs.org/cli-cursor/-/cli-cursor-2.1.0.tgz";
        sha1 = "b35dac376479facc3e94747d41d0d0f5238ffcb5";
      };
    };
    "cli-spinners-1.3.1" = {
      name = "cli-spinners";
      packageName = "cli-spinners";
      version = "1.3.1";
      src = fetchurl {
        url = "https://registry.npmjs.org/cli-spinners/-/cli-spinners-1.3.1.tgz";
        sha512 = "1vad3gya61nh9npwcrcrq0d7sq9v0a2zaqvvnhbzpqxfp24qkh3xb8372fk9yx7l1nm9gz2gvzjysksh9ggwlvzah1lp816ivkzh0nm";
      };
    };
    "cliui-3.2.0" = {
      name = "cliui";
      packageName = "cliui";
      version = "3.2.0";
      src = fetchurl {
        url = "https://registry.npmjs.org/cliui/-/cliui-3.2.0.tgz";
        sha1 = "120601537a916d29940f934da3b48d585a39213d";
      };
    };
    "code-point-at-1.1.0" = {
      name = "code-point-at";
      packageName = "code-point-at";
      version = "1.1.0";
      src = fetchurl {
        url = "https://registry.npmjs.org/code-point-at/-/code-point-at-1.1.0.tgz";
        sha1 = "0d070b4d043a5bea33a2f1a40e2edb3d9a4ccf77";
      };
    };
    "color-convert-1.9.1" = {
      name = "color-convert";
      packageName = "color-convert";
      version = "1.9.1";
      src = fetchurl {
        url = "https://registry.npmjs.org/color-convert/-/color-convert-1.9.1.tgz";
        sha512 = "32rj1090g95xcvm0d2ya6jbqdhiy9w2wv3picdy33fzrm455v0gi7g4n8lw0n31g37wwbdnz7lxjsisgbsaqz1d10j9nh5hi2f9lccs";
      };
    };
    "color-name-1.1.3" = {
      name = "color-name";
      packageName = "color-name";
      version = "1.1.3";
      src = fetchurl {
        url = "https://registry.npmjs.org/color-name/-/color-name-1.1.3.tgz";
        sha1 = "a7d0558bd89c42f795dd42328f740831ca53bc25";
      };
    };
    "concat-map-0.0.1" = {
      name = "concat-map";
      packageName = "concat-map";
      version = "0.0.1";
      src = fetchurl {
        url = "https://registry.npmjs.org/concat-map/-/concat-map-0.0.1.tgz";
        sha1 = "d8a96bd77fd68df7793a73036a3ba0d5405d477b";
      };
    };
    "core-util-is-1.0.2" = {
      name = "core-util-is";
      packageName = "core-util-is";
      version = "1.0.2";
      src = fetchurl {
        url = "https://registry.npmjs.org/core-util-is/-/core-util-is-1.0.2.tgz";
        sha1 = "b5fd54220aa2bc5ab57aab7140c940754503c1a7";
      };
    };
    "cosmiconfig-2.2.2" = {
      name = "cosmiconfig";
      packageName = "cosmiconfig";
      version = "2.2.2";
      src = fetchurl {
        url = "https://registry.npmjs.org/cosmiconfig/-/cosmiconfig-2.2.2.tgz";
        sha512 = "3j2bwqqxpllfpdbnnjl2n380q8mcvz08p2xi5c7kzhqrscl8f3lmpa11jzsn76b5q2rz4604bffg2vxbbx4rrlmvgr82g8500pmf8qs";
      };
    };
    "cross-spawn-5.1.0" = {
      name = "cross-spawn";
      packageName = "cross-spawn";
      version = "5.1.0";
      src = fetchurl {
        url = "https://registry.npmjs.org/cross-spawn/-/cross-spawn-5.1.0.tgz";
        sha1 = "e8bd0efee58fcff6f8f94510a0a554bbfa235449";
      };
    };
    "decamelize-1.2.0" = {
      name = "decamelize";
      packageName = "decamelize";
      version = "1.2.0";
      src = fetchurl {
        url = "https://registry.npmjs.org/decamelize/-/decamelize-1.2.0.tgz";
        sha1 = "f6534d15148269b20352e7bee26f501f9a191290";
      };
    };
    "dependency-graph-0.5.2" = {
      name = "dependency-graph";
      packageName = "dependency-graph";
      version = "0.5.2";
      src = fetchurl {
        url = "https://registry.npmjs.org/dependency-graph/-/dependency-graph-0.5.2.tgz";
        sha512 = "3ccc4xgm7n3krxxj0vx1hld7xh5z5wjh3h59ac2wrb369wcka9cjgwy815xfq8bzd2c2g16axbwi7vwvihvaf04wwxiknd74whprqby";
      };
    };
    "error-ex-1.3.1" = {
      name = "error-ex";
      packageName = "error-ex";
      version = "1.3.1";
      src = fetchurl {
        url = "https://registry.npmjs.org/error-ex/-/error-ex-1.3.1.tgz";
        sha1 = "f855a86ce61adc4e8621c3cda21e7a7612c3a8dc";
      };
    };
    "escape-string-regexp-1.0.5" = {
      name = "escape-string-regexp";
      packageName = "escape-string-regexp";
      version = "1.0.5";
      src = fetchurl {
        url = "https://registry.npmjs.org/escape-string-regexp/-/escape-string-regexp-1.0.5.tgz";
        sha1 = "1b61c0562190a8dff6ae3bb2cf0200ca130b86d4";
      };
    };
    "esprima-4.0.0" = {
      name = "esprima";
      packageName = "esprima";
      version = "4.0.0";
      src = fetchurl {
        url = "https://registry.npmjs.org/esprima/-/esprima-4.0.0.tgz";
        sha512 = "27mkhd94y9vrr8pb97br0ym5h85rawwb0biswgwdfp31x0387y12k9p9598bi4fc83fif6crfzqiqmmjs4x7gcb22ml3z1fldqm7yx1";
      };
    };
    "execa-0.7.0" = {
      name = "execa";
      packageName = "execa";
      version = "0.7.0";
      src = fetchurl {
        url = "https://registry.npmjs.org/execa/-/execa-0.7.0.tgz";
        sha1 = "944becd34cc41ee32a63a9faf27ad5a65fc59777";
      };
    };
    "expand-brackets-0.1.5" = {
      name = "expand-brackets";
      packageName = "expand-brackets";
      version = "0.1.5";
      src = fetchurl {
        url = "https://registry.npmjs.org/expand-brackets/-/expand-brackets-0.1.5.tgz";
        sha1 = "df07284e342a807cd733ac5af72411e581d1177b";
      };
    };
    "expand-range-1.8.2" = {
      name = "expand-range";
      packageName = "expand-range";
      version = "1.8.2";
      src = fetchurl {
        url = "https://registry.npmjs.org/expand-range/-/expand-range-1.8.2.tgz";
        sha1 = "a299effd335fe2721ebae8e257ec79644fc85337";
      };
    };
    "extglob-0.3.2" = {
      name = "extglob";
      packageName = "extglob";
      version = "0.3.2";
      src = fetchurl {
        url = "https://registry.npmjs.org/extglob/-/extglob-0.3.2.tgz";
        sha1 = "2e18ff3d2f49ab2765cec9023f011daa8d8349a1";
      };
    };
    "filename-regex-2.0.1" = {
      name = "filename-regex";
      packageName = "filename-regex";
      version = "2.0.1";
      src = fetchurl {
        url = "https://registry.npmjs.org/filename-regex/-/filename-regex-2.0.1.tgz";
        sha1 = "c1c4b9bee3e09725ddb106b75c1e301fe2f18b26";
      };
    };
    "fill-range-2.2.4" = {
      name = "fill-range";
      packageName = "fill-range";
      version = "2.2.4";
      src = fetchurl {
        url = "https://registry.npmjs.org/fill-range/-/fill-range-2.2.4.tgz";
        sha512 = "3jpxxzv8ji9xqk6xwbr20nsl31jjqr5asnv0ayixyc3r393yv4r44b7lifpk1pqaw8clzs0cy7dnw9yb5axpg9ih7vfimzlp04xqykj";
      };
    };
    "find-up-2.1.0" = {
      name = "find-up";
      packageName = "find-up";
      version = "2.1.0";
      src = fetchurl {
        url = "https://registry.npmjs.org/find-up/-/find-up-2.1.0.tgz";
        sha1 = "45d1b7e506c717ddd482775a2b77920a3c0c57a7";
      };
    };
    "for-in-1.0.2" = {
      name = "for-in";
      packageName = "for-in";
      version = "1.0.2";
      src = fetchurl {
        url = "https://registry.npmjs.org/for-in/-/for-in-1.0.2.tgz";
        sha1 = "81068d295a8142ec0ac726c6e2200c30fb6d5e80";
      };
    };
    "for-own-0.1.5" = {
      name = "for-own";
      packageName = "for-own";
      version = "0.1.5";
      src = fetchurl {
        url = "https://registry.npmjs.org/for-own/-/for-own-0.1.5.tgz";
        sha1 = "5265c681a4f294dabbf17c9509b6763aa84510ce";
      };
    };
    "fs-extra-3.0.1" = {
      name = "fs-extra";
      packageName = "fs-extra";
      version = "3.0.1";
      src = fetchurl {
        url = "https://registry.npmjs.org/fs-extra/-/fs-extra-3.0.1.tgz";
        sha1 = "3794f378c58b342ea7dbbb23095109c4b3b62291";
      };
    };
    "fs.realpath-1.0.0" = {
      name = "fs.realpath";
      packageName = "fs.realpath";
      version = "1.0.0";
      src = fetchurl {
        url = "https://registry.npmjs.org/fs.realpath/-/fs.realpath-1.0.0.tgz";
        sha1 = "1504ad2523158caa40db4a2787cb01411994ea4f";
      };
    };
    "fsevents-1.2.4" = {
      name = "fsevents";
      packageName = "fsevents";
      version = "1.2.4";
      src = fetchurl {
        url = "https://registry.npmjs.org/fsevents/-/fsevents-1.2.4.tgz";
        sha512 = "0vfzl6byj55zmi8xiqb9bqd5q0awlpgz4hsph9xzhzrd46did859d6fp5vydh7n4d0n1ph5q36smq6k3pjq6w5fxs0vx4xjv3yzrhfg";
      };
    };
    "get-caller-file-1.0.2" = {
      name = "get-caller-file";
      packageName = "get-caller-file";
      version = "1.0.2";
      src = fetchurl {
        url = "https://registry.npmjs.org/get-caller-file/-/get-caller-file-1.0.2.tgz";
        sha1 = "f702e63127e7e231c160a80c1554acb70d5047e5";
      };
    };
    "get-stdin-5.0.1" = {
      name = "get-stdin";
      packageName = "get-stdin";
      version = "5.0.1";
      src = fetchurl {
        url = "https://registry.npmjs.org/get-stdin/-/get-stdin-5.0.1.tgz";
        sha1 = "122e161591e21ff4c52530305693f20e6393a398";
      };
    };
    "get-stream-3.0.0" = {
      name = "get-stream";
      packageName = "get-stream";
      version = "3.0.0";
      src = fetchurl {
        url = "https://registry.npmjs.org/get-stream/-/get-stream-3.0.0.tgz";
        sha1 = "8e943d1358dc37555054ecbe2edb05aa174ede14";
      };
    };
    "glob-7.1.2" = {
      name = "glob";
      packageName = "glob";
      version = "7.1.2";
      src = fetchurl {
        url = "https://registry.npmjs.org/glob/-/glob-7.1.2.tgz";
        sha512 = "08vjxzixc9dwc1hn5pd60yyij98krk2pr758aiga97r02ncvaqx1hidi95wk470k1v84gg4alls9bm52m77174z128bgf13b61x951h";
      };
    };
    "glob-base-0.3.0" = {
      name = "glob-base";
      packageName = "glob-base";
      version = "0.3.0";
      src = fetchurl {
        url = "https://registry.npmjs.org/glob-base/-/glob-base-0.3.0.tgz";
        sha1 = "dbb164f6221b1c0b1ccf82aea328b497df0ea3c4";
      };
    };
    "glob-parent-2.0.0" = {
      name = "glob-parent";
      packageName = "glob-parent";
      version = "2.0.0";
      src = fetchurl {
        url = "https://registry.npmjs.org/glob-parent/-/glob-parent-2.0.0.tgz";
        sha1 = "81383d72db054fcccf5336daa902f182f6edbb28";
      };
    };
    "globby-6.1.0" = {
      name = "globby";
      packageName = "globby";
      version = "6.1.0";
      src = fetchurl {
        url = "https://registry.npmjs.org/globby/-/globby-6.1.0.tgz";
        sha1 = "f5a6d70e8395e21c858fb0489d64df02424d506c";
      };
    };
    "graceful-fs-4.1.11" = {
      name = "graceful-fs";
      packageName = "graceful-fs";
      version = "4.1.11";
      src = fetchurl {
        url = "https://registry.npmjs.org/graceful-fs/-/graceful-fs-4.1.11.tgz";
        sha1 = "0e8bdfe4d1ddb8854d64e04ea7c00e2a026e5658";
      };
    };
    "has-ansi-2.0.0" = {
      name = "has-ansi";
      packageName = "has-ansi";
      version = "2.0.0";
      src = fetchurl {
        url = "https://registry.npmjs.org/has-ansi/-/has-ansi-2.0.0.tgz";
        sha1 = "34f5049ce1ecdf2b0649af3ef24e45ed35416d91";
      };
    };
    "has-flag-3.0.0" = {
      name = "has-flag";
      packageName = "has-flag";
      version = "3.0.0";
      src = fetchurl {
        url = "https://registry.npmjs.org/has-flag/-/has-flag-3.0.0.tgz";
        sha1 = "b5d454dc2199ae225699f3467e5a07f3b955bafd";
      };
    };
    "hosted-git-info-2.6.0" = {
      name = "hosted-git-info";
      packageName = "hosted-git-info";
      version = "2.6.0";
      src = fetchurl {
        url = "https://registry.npmjs.org/hosted-git-info/-/hosted-git-info-2.6.0.tgz";
        sha512 = "1vi4baj130s7mladvb4rad9ka8nqzcwws9i1zaaplp0fdrmnfwjfbpq01cghha2c2frd2f900f07awglhbbyym0bpwmrph0hhhf11ll";
      };
    };
    "inflight-1.0.6" = {
      name = "inflight";
      packageName = "inflight";
      version = "1.0.6";
      src = fetchurl {
        url = "https://registry.npmjs.org/inflight/-/inflight-1.0.6.tgz";
        sha1 = "49bd6331d7d02d0c09bc910a1075ba8165b56df9";
      };
    };
    "inherits-2.0.3" = {
      name = "inherits";
      packageName = "inherits";
      version = "2.0.3";
      src = fetchurl {
        url = "https://registry.npmjs.org/inherits/-/inherits-2.0.3.tgz";
        sha1 = "633c2c83e3da42a502f52466022480f4208261de";
      };
    };
    "invert-kv-1.0.0" = {
      name = "invert-kv";
      packageName = "invert-kv";
      version = "1.0.0";
      src = fetchurl {
        url = "https://registry.npmjs.org/invert-kv/-/invert-kv-1.0.0.tgz";
        sha1 = "104a8e4aaca6d3d8cd157a8ef8bfab2d7a3ffdb6";
      };
    };
    "is-arrayish-0.2.1" = {
      name = "is-arrayish";
      packageName = "is-arrayish";
      version = "0.2.1";
      src = fetchurl {
        url = "https://registry.npmjs.org/is-arrayish/-/is-arrayish-0.2.1.tgz";
        sha1 = "77c99840527aa8ecb1a8ba697b80645a7a926a9d";
      };
    };
    "is-binary-path-1.0.1" = {
      name = "is-binary-path";
      packageName = "is-binary-path";
      version = "1.0.1";
      src = fetchurl {
        url = "https://registry.npmjs.org/is-binary-path/-/is-binary-path-1.0.1.tgz";
        sha1 = "75f16642b480f187a711c814161fd3a4a7655898";
      };
    };
    "is-buffer-1.1.6" = {
      name = "is-buffer";
      packageName = "is-buffer";
      version = "1.1.6";
      src = fetchurl {
        url = "https://registry.npmjs.org/is-buffer/-/is-buffer-1.1.6.tgz";
        sha512 = "3kr8dm9qyklmm2xyiz75s8db90bfilfals4x0g276kncihrrrz0ar4y6dqpvc7pwy7h43jay1bayi1r62x97nzvcswkk4ap18pl1irm";
      };
    };
    "is-builtin-module-1.0.0" = {
      name = "is-builtin-module";
      packageName = "is-builtin-module";
      version = "1.0.0";
      src = fetchurl {
        url = "https://registry.npmjs.org/is-builtin-module/-/is-builtin-module-1.0.0.tgz";
        sha1 = "540572d34f7ac3119f8f76c30cbc1b1e037affbe";
      };
    };
    "is-directory-0.3.1" = {
      name = "is-directory";
      packageName = "is-directory";
      version = "0.3.1";
      src = fetchurl {
        url = "https://registry.npmjs.org/is-directory/-/is-directory-0.3.1.tgz";
        sha1 = "61339b6f2475fc772fd9c9d83f5c8575dc154ae1";
      };
    };
    "is-dotfile-1.0.3" = {
      name = "is-dotfile";
      packageName = "is-dotfile";
      version = "1.0.3";
      src = fetchurl {
        url = "https://registry.npmjs.org/is-dotfile/-/is-dotfile-1.0.3.tgz";
        sha1 = "a6a2f32ffd2dfb04f5ca25ecd0f6b83cf798a1e1";
      };
    };
    "is-equal-shallow-0.1.3" = {
      name = "is-equal-shallow";
      packageName = "is-equal-shallow";
      version = "0.1.3";
      src = fetchurl {
        url = "https://registry.npmjs.org/is-equal-shallow/-/is-equal-shallow-0.1.3.tgz";
        sha1 = "2238098fc221de0bcfa5d9eac4c45d638aa1c534";
      };
    };
    "is-extendable-0.1.1" = {
      name = "is-extendable";
      packageName = "is-extendable";
      version = "0.1.1";
      src = fetchurl {
        url = "https://registry.npmjs.org/is-extendable/-/is-extendable-0.1.1.tgz";
        sha1 = "62b110e289a471418e3ec36a617d472e301dfc89";
      };
    };
    "is-extglob-1.0.0" = {
      name = "is-extglob";
      packageName = "is-extglob";
      version = "1.0.0";
      src = fetchurl {
        url = "https://registry.npmjs.org/is-extglob/-/is-extglob-1.0.0.tgz";
        sha1 = "ac468177c4943405a092fc8f29760c6ffc6206c0";
      };
    };
    "is-fullwidth-code-point-1.0.0" = {
      name = "is-fullwidth-code-point";
      packageName = "is-fullwidth-code-point";
      version = "1.0.0";
      src = fetchurl {
        url = "https://registry.npmjs.org/is-fullwidth-code-point/-/is-fullwidth-code-point-1.0.0.tgz";
        sha1 = "ef9e31386f031a7f0d643af82fde50c457ef00cb";
      };
    };
    "is-fullwidth-code-point-2.0.0" = {
      name = "is-fullwidth-code-point";
      packageName = "is-fullwidth-code-point";
      version = "2.0.0";
      src = fetchurl {
        url = "https://registry.npmjs.org/is-fullwidth-code-point/-/is-fullwidth-code-point-2.0.0.tgz";
        sha1 = "a3b30a5c4f199183167aaab93beefae3ddfb654f";
      };
    };
    "is-glob-2.0.1" = {
      name = "is-glob";
      packageName = "is-glob";
      version = "2.0.1";
      src = fetchurl {
        url = "https://registry.npmjs.org/is-glob/-/is-glob-2.0.1.tgz";
        sha1 = "d096f926a3ded5600f3fdfd91198cb0888c2d863";
      };
    };
    "is-number-2.1.0" = {
      name = "is-number";
      packageName = "is-number";
      version = "2.1.0";
      src = fetchurl {
        url = "https://registry.npmjs.org/is-number/-/is-number-2.1.0.tgz";
        sha1 = "01fcbbb393463a548f2f466cce16dece49db908f";
      };
    };
    "is-number-4.0.0" = {
      name = "is-number";
      packageName = "is-number";
      version = "4.0.0";
      src = fetchurl {
        url = "https://registry.npmjs.org/is-number/-/is-number-4.0.0.tgz";
        sha512 = "20ybhnkgsrcwv730ch8qvzayjwcvs83jk2w6iim7wv3h2nn4jz8hsldn0k6ggx4xgcypwirqjb5xdacsswsk06w2nk56zr509q2aadd";
      };
    };
    "is-posix-bracket-0.1.1" = {
      name = "is-posix-bracket";
      packageName = "is-posix-bracket";
      version = "0.1.1";
      src = fetchurl {
        url = "https://registry.npmjs.org/is-posix-bracket/-/is-posix-bracket-0.1.1.tgz";
        sha1 = "3334dc79774368e92f016e6fbc0a88f5cd6e6bc4";
      };
    };
    "is-primitive-2.0.0" = {
      name = "is-primitive";
      packageName = "is-primitive";
      version = "2.0.0";
      src = fetchurl {
        url = "https://registry.npmjs.org/is-primitive/-/is-primitive-2.0.0.tgz";
        sha1 = "207bab91638499c07b2adf240a41a87210034575";
      };
    };
    "is-stream-1.1.0" = {
      name = "is-stream";
      packageName = "is-stream";
      version = "1.1.0";
      src = fetchurl {
        url = "https://registry.npmjs.org/is-stream/-/is-stream-1.1.0.tgz";
        sha1 = "12d4a3dd4e68e0b79ceb8dbc84173ae80d91ca44";
      };
    };
    "isarray-1.0.0" = {
      name = "isarray";
      packageName = "isarray";
      version = "1.0.0";
      src = fetchurl {
        url = "https://registry.npmjs.org/isarray/-/isarray-1.0.0.tgz";
        sha1 = "bb935d48582cba168c06834957a54a3e07124f11";
      };
    };
    "isexe-2.0.0" = {
      name = "isexe";
      packageName = "isexe";
      version = "2.0.0";
      src = fetchurl {
        url = "https://registry.npmjs.org/isexe/-/isexe-2.0.0.tgz";
        sha1 = "e8fbf374dc556ff8947a10dcb0572d633f2cfa10";
      };
    };
    "isobject-2.1.0" = {
      name = "isobject";
      packageName = "isobject";
      version = "2.1.0";
      src = fetchurl {
        url = "https://registry.npmjs.org/isobject/-/isobject-2.1.0.tgz";
        sha1 = "f065561096a3f1da2ef46272f815c840d87e0c89";
      };
    };
    "js-yaml-3.12.0" = {
      name = "js-yaml";
      packageName = "js-yaml";
      version = "3.12.0";
      src = fetchurl {
        url = "https://registry.npmjs.org/js-yaml/-/js-yaml-3.12.0.tgz";
        sha512 = "3f8k2gvi3gnj9gpr3dnm5n5vpy2w68pshqk4hajlsmkb37ky30cnqza82l8sq153zx1nk67gizcm1ngmvlajw53hkwg4g96gir7d2rw";
      };
    };
    "jsonfile-3.0.1" = {
      name = "jsonfile";
      packageName = "jsonfile";
      version = "3.0.1";
      src = fetchurl {
        url = "https://registry.npmjs.org/jsonfile/-/jsonfile-3.0.1.tgz";
        sha1 = "a5ecc6f65f53f662c4415c7675a0331d0992ec66";
      };
    };
    "kind-of-3.2.2" = {
      name = "kind-of";
      packageName = "kind-of";
      version = "3.2.2";
      src = fetchurl {
        url = "https://registry.npmjs.org/kind-of/-/kind-of-3.2.2.tgz";
        sha1 = "31ea21a734bab9bbb0f32466d893aea51e4a3c64";
      };
    };
    "kind-of-6.0.2" = {
      name = "kind-of";
      packageName = "kind-of";
      version = "6.0.2";
      src = fetchurl {
        url = "https://registry.npmjs.org/kind-of/-/kind-of-6.0.2.tgz";
        sha512 = "2l91vcracq8y3nxacsssb4yhk0ww011gi5sn55wsb6bpnhyds2i1x98512f61r8awxmj602bxky6c7hsyibjvz17f1pmlf7r4whp6dk";
      };
    };
    "lcid-1.0.0" = {
      name = "lcid";
      packageName = "lcid";
      version = "1.0.0";
      src = fetchurl {
        url = "https://registry.npmjs.org/lcid/-/lcid-1.0.0.tgz";
        sha1 = "308accafa0bc483a3867b4b6f2b9506251d1b835";
      };
    };
    "load-json-file-2.0.0" = {
      name = "load-json-file";
      packageName = "load-json-file";
      version = "2.0.0";
      src = fetchurl {
        url = "https://registry.npmjs.org/load-json-file/-/load-json-file-2.0.0.tgz";
        sha1 = "7947e42149af80d696cbf797bcaabcfe1fe29ca8";
      };
    };
    "locate-path-2.0.0" = {
      name = "locate-path";
      packageName = "locate-path";
      version = "2.0.0";
      src = fetchurl {
        url = "https://registry.npmjs.org/locate-path/-/locate-path-2.0.0.tgz";
        sha1 = "2b568b265eec944c6d9c0de9c3dbbbca0354cd8e";
      };
    };
    "lodash-4.17.10" = {
      name = "lodash";
      packageName = "lodash";
      version = "4.17.10";
      src = fetchurl {
        url = "https://registry.npmjs.org/lodash/-/lodash-4.17.10.tgz";
        sha512 = "1ba5b80jjzwrh9fbdk5ywv8sic0dynij21wgrfxsfjzwvwd7x1n6azdhdc0vjdxqmcpm0mhshd1k7n2ascxpz00z3p8a3k97mwg1s2i";
      };
    };
    "log-symbols-1.0.2" = {
      name = "log-symbols";
      packageName = "log-symbols";
      version = "1.0.2";
      src = fetchurl {
        url = "https://registry.npmjs.org/log-symbols/-/log-symbols-1.0.2.tgz";
        sha1 = "376ff7b58ea3086a0f09facc74617eca501e1a18";
      };
    };
    "log-symbols-2.2.0" = {
      name = "log-symbols";
      packageName = "log-symbols";
      version = "2.2.0";
      src = fetchurl {
        url = "https://registry.npmjs.org/log-symbols/-/log-symbols-2.2.0.tgz";
        sha512 = "093j1mha2zwbfkb6cvxr94l1dsx44607vvyxadxki3j69s40n2f6x6iqs6f9rzpvvqd8anclsqdlrm3klkwxixm4k2fl8bjr4b01qjm";
      };
    };
    "lru-cache-4.1.3" = {
      name = "lru-cache";
      packageName = "lru-cache";
      version = "4.1.3";
      src = fetchurl {
        url = "https://registry.npmjs.org/lru-cache/-/lru-cache-4.1.3.tgz";
        sha512 = "0j2ny2y61f70dbzarfa1xazv68dw7nb2r4p5sy46fw6dwr9y0yg003lb1yv7sdl77hcrpzn22mih799z657sz21al4qmf1kr2yj2lbw";
      };
    };
    "math-random-1.0.1" = {
      name = "math-random";
      packageName = "math-random";
      version = "1.0.1";
      src = fetchurl {
        url = "https://registry.npmjs.org/math-random/-/math-random-1.0.1.tgz";
        sha1 = "8b3aac588b8a66e4975e3cdea67f7bb329601fac";
      };
    };
    "mem-1.1.0" = {
      name = "mem";
      packageName = "mem";
      version = "1.1.0";
      src = fetchurl {
        url = "https://registry.npmjs.org/mem/-/mem-1.1.0.tgz";
        sha1 = "5edd52b485ca1d900fe64895505399a0dfa45f76";
      };
    };
    "micromatch-2.3.11" = {
      name = "micromatch";
      packageName = "micromatch";
      version = "2.3.11";
      src = fetchurl {
        url = "https://registry.npmjs.org/micromatch/-/micromatch-2.3.11.tgz";
        sha1 = "86677c97d1720b363431d04d0d15293bd38c1565";
      };
    };
    "mimic-fn-1.2.0" = {
      name = "mimic-fn";
      packageName = "mimic-fn";
      version = "1.2.0";
      src = fetchurl {
        url = "https://registry.npmjs.org/mimic-fn/-/mimic-fn-1.2.0.tgz";
        sha512 = "1clrrqw75rmpkw0x53axy8va2hq2gzynz9zb58m0xv1nh3lg81cv4dfdy7pk9vrlb9ydwmj6klpicwkv2bjx3m8aj4fi2ph3jxkizwd";
      };
    };
    "minimatch-3.0.4" = {
      name = "minimatch";
      packageName = "minimatch";
      version = "3.0.4";
      src = fetchurl {
        url = "https://registry.npmjs.org/minimatch/-/minimatch-3.0.4.tgz";
        sha512 = "1879a3j85h92ypvb7lpv1dqpcxl49rqnbgs5la18zmj1yqhwl60c2m74254wbr5pp3znckqpkg9dvjyrz6hfz8b9vag5a3j910db4f8";
      };
    };
    "minimist-1.2.0" = {
      name = "minimist";
      packageName = "minimist";
      version = "1.2.0";
      src = fetchurl {
        url = "https://registry.npmjs.org/minimist/-/minimist-1.2.0.tgz";
        sha1 = "a35008b20f41383eec1fb914f4cd5df79a264284";
      };
    };
    "nan-2.10.0" = {
      name = "nan";
      packageName = "nan";
      version = "2.10.0";
      src = fetchurl {
        url = "https://registry.npmjs.org/nan/-/nan-2.10.0.tgz";
        sha512 = "349rr7x0djrlkav4gbhkg355852ingn965r0kkch8rr4cwp7qki9676zpq8cq988yszzd2hld6szsbbnd1v6rghzf11abn1nyzlj1vc";
      };
    };
    "normalize-package-data-2.4.0" = {
      name = "normalize-package-data";
      packageName = "normalize-package-data";
      version = "2.4.0";
      src = fetchurl {
        url = "https://registry.npmjs.org/normalize-package-data/-/normalize-package-data-2.4.0.tgz";
        sha512 = "01wzws79ps84ylshjb7rfpjykgiqxnpr89s52p2yyzfx8nfvyh5flvf1almiiavsi75xgi8g3s5davc1mmgz7gn8yvlqz6gnhax8f7n";
      };
    };
    "normalize-path-2.1.1" = {
      name = "normalize-path";
      packageName = "normalize-path";
      version = "2.1.1";
      src = fetchurl {
        url = "https://registry.npmjs.org/normalize-path/-/normalize-path-2.1.1.tgz";
        sha1 = "1ab28b556e198363a8c1a6f7e6fa20137fe6aed9";
      };
    };
    "npm-run-path-2.0.2" = {
      name = "npm-run-path";
      packageName = "npm-run-path";
      version = "2.0.2";
      src = fetchurl {
        url = "https://registry.npmjs.org/npm-run-path/-/npm-run-path-2.0.2.tgz";
        sha1 = "35a9232dfa35d7067b4cb2ddf2357b1871536c5f";
      };
    };
    "number-is-nan-1.0.1" = {
      name = "number-is-nan";
      packageName = "number-is-nan";
      version = "1.0.1";
      src = fetchurl {
        url = "https://registry.npmjs.org/number-is-nan/-/number-is-nan-1.0.1.tgz";
        sha1 = "097b602b53422a522c1afb8790318336941a011d";
      };
    };
    "object-assign-4.1.1" = {
      name = "object-assign";
      packageName = "object-assign";
      version = "4.1.1";
      src = fetchurl {
        url = "https://registry.npmjs.org/object-assign/-/object-assign-4.1.1.tgz";
        sha1 = "2109adc7965887cfc05cbbd442cac8bfbb360863";
      };
    };
    "object.omit-2.0.1" = {
      name = "object.omit";
      packageName = "object.omit";
      version = "2.0.1";
      src = fetchurl {
        url = "https://registry.npmjs.org/object.omit/-/object.omit-2.0.1.tgz";
        sha1 = "1a9c744829f39dbb858c76ca3579ae2a54ebd1fa";
      };
    };
    "once-1.4.0" = {
      name = "once";
      packageName = "once";
      version = "1.4.0";
      src = fetchurl {
        url = "https://registry.npmjs.org/once/-/once-1.4.0.tgz";
        sha1 = "583b1aa775961d4b113ac17d9c50baef9dd76bd1";
      };
    };
    "onetime-2.0.1" = {
      name = "onetime";
      packageName = "onetime";
      version = "2.0.1";
      src = fetchurl {
        url = "https://registry.npmjs.org/onetime/-/onetime-2.0.1.tgz";
        sha1 = "067428230fd67443b2794b22bba528b6867962d4";
      };
    };
    "ora-1.4.0" = {
      name = "ora";
      packageName = "ora";
      version = "1.4.0";
      src = fetchurl {
        url = "https://registry.npmjs.org/ora/-/ora-1.4.0.tgz";
        sha512 = "2kz616isg6vqp95rsja7fc47k22qipv9b44dhsyxsl7x95ly9j17dwn8dxq8adyhw6ap1nlpfg2dk8v6r7b2m8r61v3ikriwh6bbhl8";
      };
    };
    "os-homedir-1.0.2" = {
      name = "os-homedir";
      packageName = "os-homedir";
      version = "1.0.2";
      src = fetchurl {
        url = "https://registry.npmjs.org/os-homedir/-/os-homedir-1.0.2.tgz";
        sha1 = "ffbc4988336e0e833de0c168c7ef152121aa7fb3";
      };
    };
    "os-locale-2.1.0" = {
      name = "os-locale";
      packageName = "os-locale";
      version = "2.1.0";
      src = fetchurl {
        url = "https://registry.npmjs.org/os-locale/-/os-locale-2.1.0.tgz";
        sha512 = "0lafrp0i2ajapsnma0x74q7zscn97a56i5hh58a0nyig2igfx9fqn4ain9kvjrr06as5gzdrv2wdf52qc5m861fd0f4cv69ghdjbjyy";
      };
    };
    "p-finally-1.0.0" = {
      name = "p-finally";
      packageName = "p-finally";
      version = "1.0.0";
      src = fetchurl {
        url = "https://registry.npmjs.org/p-finally/-/p-finally-1.0.0.tgz";
        sha1 = "3fbcfb15b899a44123b34b6dcc18b724336a2cae";
      };
    };
    "p-limit-1.3.0" = {
      name = "p-limit";
      packageName = "p-limit";
      version = "1.3.0";
      src = fetchurl {
        url = "https://registry.npmjs.org/p-limit/-/p-limit-1.3.0.tgz";
        sha512 = "3sh18calqxbww99pxc84hldflmj0i915g8npihlmazw8wjqabihi9475v0ll3fhx44sxn35j014j1k5d2xr73q3mpwkmx09n2q1gxxy";
      };
    };
    "p-locate-2.0.0" = {
      name = "p-locate";
      packageName = "p-locate";
      version = "2.0.0";
      src = fetchurl {
        url = "https://registry.npmjs.org/p-locate/-/p-locate-2.0.0.tgz";
        sha1 = "20a0103b222a70c8fd39cc2e580680f3dde5ec43";
      };
    };
    "p-try-1.0.0" = {
      name = "p-try";
      packageName = "p-try";
      version = "1.0.0";
      src = fetchurl {
        url = "https://registry.npmjs.org/p-try/-/p-try-1.0.0.tgz";
        sha1 = "cbc79cdbaf8fd4228e13f621f2b1a237c1b207b3";
      };
    };
    "parse-glob-3.0.4" = {
      name = "parse-glob";
      packageName = "parse-glob";
      version = "3.0.4";
      src = fetchurl {
        url = "https://registry.npmjs.org/parse-glob/-/parse-glob-3.0.4.tgz";
        sha1 = "b2c376cfb11f35513badd173ef0bb6e3a388391c";
      };
    };
    "parse-json-2.2.0" = {
      name = "parse-json";
      packageName = "parse-json";
      version = "2.2.0";
      src = fetchurl {
        url = "https://registry.npmjs.org/parse-json/-/parse-json-2.2.0.tgz";
        sha1 = "f480f40434ef80741f8469099f8dea18f55a4dc9";
      };
    };
    "path-exists-3.0.0" = {
      name = "path-exists";
      packageName = "path-exists";
      version = "3.0.0";
      src = fetchurl {
        url = "https://registry.npmjs.org/path-exists/-/path-exists-3.0.0.tgz";
        sha1 = "ce0ebeaa5f78cb18925ea7d810d7b59b010fd515";
      };
    };
    "path-is-absolute-1.0.1" = {
      name = "path-is-absolute";
      packageName = "path-is-absolute";
      version = "1.0.1";
      src = fetchurl {
        url = "https://registry.npmjs.org/path-is-absolute/-/path-is-absolute-1.0.1.tgz";
        sha1 = "174b9268735534ffbc7ace6bf53a5a9e1b5c5f5f";
      };
    };
    "path-key-2.0.1" = {
      name = "path-key";
      packageName = "path-key";
      version = "2.0.1";
      src = fetchurl {
        url = "https://registry.npmjs.org/path-key/-/path-key-2.0.1.tgz";
        sha1 = "411cadb574c5a140d3a4b1910d40d80cc9f40b40";
      };
    };
    "path-type-2.0.0" = {
      name = "path-type";
      packageName = "path-type";
      version = "2.0.0";
      src = fetchurl {
        url = "https://registry.npmjs.org/path-type/-/path-type-2.0.0.tgz";
        sha1 = "f012ccb8415b7096fc2daa1054c3d72389594c73";
      };
    };
    "pify-2.3.0" = {
      name = "pify";
      packageName = "pify";
      version = "2.3.0";
      src = fetchurl {
        url = "https://registry.npmjs.org/pify/-/pify-2.3.0.tgz";
        sha1 = "ed141a6ac043a849ea588498e7dca8b15330e90c";
      };
    };
    "pinkie-2.0.4" = {
      name = "pinkie";
      packageName = "pinkie";
      version = "2.0.4";
      src = fetchurl {
        url = "https://registry.npmjs.org/pinkie/-/pinkie-2.0.4.tgz";
        sha1 = "72556b80cfa0d48a974e80e77248e80ed4f7f870";
      };
    };
    "pinkie-promise-2.0.1" = {
      name = "pinkie-promise";
      packageName = "pinkie-promise";
      version = "2.0.1";
      src = fetchurl {
        url = "https://registry.npmjs.org/pinkie-promise/-/pinkie-promise-2.0.1.tgz";
        sha1 = "2135d6dfa7a358c069ac9b178776288228450ffa";
      };
    };
    "postcss-6.0.22" = {
      name = "postcss";
      packageName = "postcss";
      version = "6.0.22";
      src = fetchurl {
        url = "https://registry.npmjs.org/postcss/-/postcss-6.0.22.tgz";
        sha512 = "0fdfvn2pq9hvw40s9l174v5rv4d5x3i9xmd8p3mln6bhzrny3v1h0y1324ghq30jnbrvyfam0725r3hsmj28lhhmc32q08lpaa3v1sf";
      };
    };
    "postcss-load-config-1.2.0" = {
      name = "postcss-load-config";
      packageName = "postcss-load-config";
      version = "1.2.0";
      src = fetchurl {
        url = "https://registry.npmjs.org/postcss-load-config/-/postcss-load-config-1.2.0.tgz";
        sha1 = "539e9afc9ddc8620121ebf9d8c3673e0ce50d28a";
      };
    };
    "postcss-load-options-1.2.0" = {
      name = "postcss-load-options";
      packageName = "postcss-load-options";
      version = "1.2.0";
      src = fetchurl {
        url = "https://registry.npmjs.org/postcss-load-options/-/postcss-load-options-1.2.0.tgz";
        sha1 = "b098b1559ddac2df04bc0bb375f99a5cfe2b6d8c";
      };
    };
    "postcss-load-plugins-2.3.0" = {
      name = "postcss-load-plugins";
      packageName = "postcss-load-plugins";
      version = "2.3.0";
      src = fetchurl {
        url = "https://registry.npmjs.org/postcss-load-plugins/-/postcss-load-plugins-2.3.0.tgz";
        sha1 = "745768116599aca2f009fad426b00175049d8d92";
      };
    };
    "postcss-reporter-4.0.0" = {
      name = "postcss-reporter";
      packageName = "postcss-reporter";
      version = "4.0.0";
      src = fetchurl {
        url = "https://registry.npmjs.org/postcss-reporter/-/postcss-reporter-4.0.0.tgz";
        sha512 = "1q9xgvdyrql0i2jgj5ir3qvyizrl76hzb42fx4pqlm8ivc496rv16b1v33lqbrmkvq1ci9nw5hb9nnd3p2ymnbnnc4b1vxn9kdp2i90";
      };
    };
    "preserve-0.2.0" = {
      name = "preserve";
      packageName = "preserve";
      version = "0.2.0";
      src = fetchurl {
        url = "https://registry.npmjs.org/preserve/-/preserve-0.2.0.tgz";
        sha1 = "815ed1f6ebc65926f865b310c0713bcb3315ce4b";
      };
    };
    "process-nextick-args-2.0.0" = {
      name = "process-nextick-args";
      packageName = "process-nextick-args";
      version = "2.0.0";
      src = fetchurl {
        url = "https://registry.npmjs.org/process-nextick-args/-/process-nextick-args-2.0.0.tgz";
        sha512 = "0rw8xpqqkhs91722slvzf8icxfaimqp4w8zb3840jxr7r8n8035byl6dhdi5bm0yr6x7sdws0gf3m025fg6hqgaklwlbl4d7bah5l9j";
      };
    };
    "pseudomap-1.0.2" = {
      name = "pseudomap";
      packageName = "pseudomap";
      version = "1.0.2";
      src = fetchurl {
        url = "https://registry.npmjs.org/pseudomap/-/pseudomap-1.0.2.tgz";
        sha1 = "f052a28da70e618917ef0a8ac34c1ae5a68286b3";
      };
    };
    "randomatic-3.0.0" = {
      name = "randomatic";
      packageName = "randomatic";
      version = "3.0.0";
      src = fetchurl {
        url = "https://registry.npmjs.org/randomatic/-/randomatic-3.0.0.tgz";
        sha512 = "142g2k8ipzpkp1sv5zsbk8qy39r5isc1s9q2x910dh6zqwdksd6mkq16apdrfw6ssv14hpg64j4zy3v4m4lclpvwi767phqh4w4bp2m";
      };
    };
    "read-cache-1.0.0" = {
      name = "read-cache";
      packageName = "read-cache";
      version = "1.0.0";
      src = fetchurl {
        url = "https://registry.npmjs.org/read-cache/-/read-cache-1.0.0.tgz";
        sha1 = "e664ef31161166c9751cdbe8dbcf86b5fb58f774";
      };
    };
    "read-pkg-2.0.0" = {
      name = "read-pkg";
      packageName = "read-pkg";
      version = "2.0.0";
      src = fetchurl {
        url = "https://registry.npmjs.org/read-pkg/-/read-pkg-2.0.0.tgz";
        sha1 = "8ef1c0623c6a6db0dc6713c4bfac46332b2368f8";
      };
    };
    "read-pkg-up-2.0.0" = {
      name = "read-pkg-up";
      packageName = "read-pkg-up";
      version = "2.0.0";
      src = fetchurl {
        url = "https://registry.npmjs.org/read-pkg-up/-/read-pkg-up-2.0.0.tgz";
        sha1 = "6b72a8048984e0c41e79510fd5e9fa99b3b549be";
      };
    };
    "readable-stream-2.3.6" = {
      name = "readable-stream";
      packageName = "readable-stream";
      version = "2.3.6";
      src = fetchurl {
        url = "https://registry.npmjs.org/readable-stream/-/readable-stream-2.3.6.tgz";
        sha512 = "0mj9b6190amln9rg89x5pq2n195s3v0gzicpdamv1kbabg69aw5m71l34jsjn7bqil7405l6l35x9ijnb3h4jz5vx2i00l8sl1ll2xm";
      };
    };
    "readdirp-2.1.0" = {
      name = "readdirp";
      packageName = "readdirp";
      version = "2.1.0";
      src = fetchurl {
        url = "https://registry.npmjs.org/readdirp/-/readdirp-2.1.0.tgz";
        sha1 = "4ed0ad060df3073300c48440373f72d1cc642d78";
      };
    };
    "regex-cache-0.4.4" = {
      name = "regex-cache";
      packageName = "regex-cache";
      version = "0.4.4";
      src = fetchurl {
        url = "https://registry.npmjs.org/regex-cache/-/regex-cache-0.4.4.tgz";
        sha512 = "1crfmf19zkv0imnbbkj7bwrcyin3zxa88cs86b6apkxj8qrsmkxnydhsy2ia75q4ld10rhi2s2c36h7g77a997mh9c2z453s311jllx";
      };
    };
    "remove-trailing-separator-1.1.0" = {
      name = "remove-trailing-separator";
      packageName = "remove-trailing-separator";
      version = "1.1.0";
      src = fetchurl {
        url = "https://registry.npmjs.org/remove-trailing-separator/-/remove-trailing-separator-1.1.0.tgz";
        sha1 = "c24bce2a283adad5bc3f58e0d48249b92379d8ef";
      };
    };
    "repeat-element-1.1.2" = {
      name = "repeat-element";
      packageName = "repeat-element";
      version = "1.1.2";
      src = fetchurl {
        url = "https://registry.npmjs.org/repeat-element/-/repeat-element-1.1.2.tgz";
        sha1 = "ef089a178d1483baae4d93eb98b4f9e4e11d990a";
      };
    };
    "repeat-string-1.6.1" = {
      name = "repeat-string";
      packageName = "repeat-string";
      version = "1.6.1";
      src = fetchurl {
        url = "https://registry.npmjs.org/repeat-string/-/repeat-string-1.6.1.tgz";
        sha1 = "8dcae470e1c88abc2d600fff4a776286da75e637";
      };
    };
    "require-directory-2.1.1" = {
      name = "require-directory";
      packageName = "require-directory";
      version = "2.1.1";
      src = fetchurl {
        url = "https://registry.npmjs.org/require-directory/-/require-directory-2.1.1.tgz";
        sha1 = "8c64ad5fd30dab1c976e2344ffe7f792a6a6df42";
      };
    };
    "require-from-string-1.2.1" = {
      name = "require-from-string";
      packageName = "require-from-string";
      version = "1.2.1";
      src = fetchurl {
        url = "https://registry.npmjs.org/require-from-string/-/require-from-string-1.2.1.tgz";
        sha1 = "529c9ccef27380adfec9a2f965b649bbee636418";
      };
    };
    "require-main-filename-1.0.1" = {
      name = "require-main-filename";
      packageName = "require-main-filename";
      version = "1.0.1";
      src = fetchurl {
        url = "https://registry.npmjs.org/require-main-filename/-/require-main-filename-1.0.1.tgz";
        sha1 = "97f717b69d48784f5f526a6c5aa8ffdda055a4d1";
      };
    };
    "restore-cursor-2.0.0" = {
      name = "restore-cursor";
      packageName = "restore-cursor";
      version = "2.0.0";
      src = fetchurl {
        url = "https://registry.npmjs.org/restore-cursor/-/restore-cursor-2.0.0.tgz";
        sha1 = "9f7ee287f82fd326d4fd162923d62129eee0dfaf";
      };
    };
    "safe-buffer-5.1.2" = {
      name = "safe-buffer";
      packageName = "safe-buffer";
      version = "5.1.2";
      src = fetchurl {
        url = "https://registry.npmjs.org/safe-buffer/-/safe-buffer-5.1.2.tgz";
        sha512 = "3xbm0dkya4bc3zwfwpdzbl8ngq0aai5ihlp2v3s39y7162c7wyvv9izj3g8hv6dy6vm2lq48lmfzygk0kxwbjb6xic7k4a329j99p8r";
      };
    };
    "semver-5.5.0" = {
      name = "semver";
      packageName = "semver";
      version = "5.5.0";
      src = fetchurl {
        url = "https://registry.npmjs.org/semver/-/semver-5.5.0.tgz";
        sha512 = "0h32zh035y8m6dzcqhcymbhwgmc8839fa1hhj0jfh9ivp9kmqfj1sbwnsnkzcn9qm3sqn38sa8ys2g4c638lpnmzjr0a0qndmv7f8p1";
      };
    };
    "set-blocking-2.0.0" = {
      name = "set-blocking";
      packageName = "set-blocking";
      version = "2.0.0";
      src = fetchurl {
        url = "https://registry.npmjs.org/set-blocking/-/set-blocking-2.0.0.tgz";
        sha1 = "045f9782d011ae9a6803ddd382b24392b3d890f7";
      };
    };
    "set-immediate-shim-1.0.1" = {
      name = "set-immediate-shim";
      packageName = "set-immediate-shim";
      version = "1.0.1";
      src = fetchurl {
        url = "https://registry.npmjs.org/set-immediate-shim/-/set-immediate-shim-1.0.1.tgz";
        sha1 = "4b2b1b27eb808a9f8dcc481a58e5e56f599f3f61";
      };
    };
    "shebang-command-1.2.0" = {
      name = "shebang-command";
      packageName = "shebang-command";
      version = "1.2.0";
      src = fetchurl {
        url = "https://registry.npmjs.org/shebang-command/-/shebang-command-1.2.0.tgz";
        sha1 = "44aac65b695b03398968c39f363fee5deafdf1ea";
      };
    };
    "shebang-regex-1.0.0" = {
      name = "shebang-regex";
      packageName = "shebang-regex";
      version = "1.0.0";
      src = fetchurl {
        url = "https://registry.npmjs.org/shebang-regex/-/shebang-regex-1.0.0.tgz";
        sha1 = "da42f49740c0b42db2ca9728571cb190c98efea3";
      };
    };
    "signal-exit-3.0.2" = {
      name = "signal-exit";
      packageName = "signal-exit";
      version = "3.0.2";
      src = fetchurl {
        url = "https://registry.npmjs.org/signal-exit/-/signal-exit-3.0.2.tgz";
        sha1 = "b5fdc08f1287ea1178628e415e25132b73646c6d";
      };
    };
    "source-map-0.6.1" = {
      name = "source-map";
      packageName = "source-map";
      version = "0.6.1";
      src = fetchurl {
        url = "https://registry.npmjs.org/source-map/-/source-map-0.6.1.tgz";
        sha512 = "3p7hw8p69ikj5mwapmqkacsjnbvdfk5ylyamjg9x5izkl717xvzj0vk3fnmx1n4pf54h5rs7r8ig5kk4jv4ycqqj0hv75cnx6k1lf2j";
      };
    };
    "spdx-correct-3.0.0" = {
      name = "spdx-correct";
      packageName = "spdx-correct";
      version = "3.0.0";
      src = fetchurl {
        url = "https://registry.npmjs.org/spdx-correct/-/spdx-correct-3.0.0.tgz";
        sha512 = "3xgkqk4hsm4nzvy68icv1rlv4s0qgb7mwpi9s4z2mp1a5fwny6kc6m4nqa7zzx2k7mrjlh7psci9lb7892bl3q4r4y2f4sw7vvnhprp";
      };
    };
    "spdx-exceptions-2.1.0" = {
      name = "spdx-exceptions";
      packageName = "spdx-exceptions";
      version = "2.1.0";
      src = fetchurl {
        url = "https://registry.npmjs.org/spdx-exceptions/-/spdx-exceptions-2.1.0.tgz";
        sha512 = "057m2ab3y8j38xb89w7d191hfaa693vbf7wnwkf302zicsgi2v5ayvcc4f03vyj4yyycqasqp3ryp2d3q0vcaq54r4ls2g5dar4vbg0";
      };
    };
    "spdx-expression-parse-3.0.0" = {
      name = "spdx-expression-parse";
      packageName = "spdx-expression-parse";
      version = "3.0.0";
      src = fetchurl {
        url = "https://registry.npmjs.org/spdx-expression-parse/-/spdx-expression-parse-3.0.0.tgz";
        sha512 = "351djgqvsgqmfg6h764c2k09dmixczw5073jirm8km6i1yym4xjrzc7g5ckwkidi3gls7s910m4ahl8sh37dsb478j8j3sigbfq63k2";
      };
    };
    "spdx-license-ids-3.0.0" = {
      name = "spdx-license-ids";
      packageName = "spdx-license-ids";
      version = "3.0.0";
      src = fetchurl {
        url = "https://registry.npmjs.org/spdx-license-ids/-/spdx-license-ids-3.0.0.tgz";
        sha512 = "066gb8vcffv2mf3lbmxvxp5b60jviw32x52n50l3zgl9z4cgwg74ca4kr4y5c3mss736bmg9nxl1lvprishbikqy0jy56770v10zqfv";
      };
    };
    "sprintf-js-1.0.3" = {
      name = "sprintf-js";
      packageName = "sprintf-js";
      version = "1.0.3";
      src = fetchurl {
        url = "https://registry.npmjs.org/sprintf-js/-/sprintf-js-1.0.3.tgz";
        sha1 = "04e6926f662895354f3dd015203633b857297e2c";
      };
    };
    "string-width-1.0.2" = {
      name = "string-width";
      packageName = "string-width";
      version = "1.0.2";
      src = fetchurl {
        url = "https://registry.npmjs.org/string-width/-/string-width-1.0.2.tgz";
        sha1 = "118bdf5b8cdc51a2a7e70d211e07e2b0b9b107d3";
      };
    };
    "string-width-2.1.1" = {
      name = "string-width";
      packageName = "string-width";
      version = "2.1.1";
      src = fetchurl {
        url = "https://registry.npmjs.org/string-width/-/string-width-2.1.1.tgz";
        sha512 = "29s1fqgr4mnhfxwczgdghfmmc1f792m9hysvcjxw2h5lfj8ndf2b6gm02m96qk5m75g4aisijvng4pk618anwbr8i9ay2jyszkqgslw";
      };
    };
    "string_decoder-1.1.1" = {
      name = "string_decoder";
      packageName = "string_decoder";
      version = "1.1.1";
      src = fetchurl {
        url = "https://registry.npmjs.org/string_decoder/-/string_decoder-1.1.1.tgz";
        sha512 = "315yd4vzwrwk3vwj1klf46y1cj2jbvf88066y2rnwhksb98phj46jkxixbwsp3h607w7czy7cby522s7sx8mvspdpdm3s72y2ga3x4z";
      };
    };
    "strip-ansi-3.0.1" = {
      name = "strip-ansi";
      packageName = "strip-ansi";
      version = "3.0.1";
      src = fetchurl {
        url = "https://registry.npmjs.org/strip-ansi/-/strip-ansi-3.0.1.tgz";
        sha1 = "6a385fb8853d952d5ff05d0e8aaf94278dc63dcf";
      };
    };
    "strip-ansi-4.0.0" = {
      name = "strip-ansi";
      packageName = "strip-ansi";
      version = "4.0.0";
      src = fetchurl {
        url = "https://registry.npmjs.org/strip-ansi/-/strip-ansi-4.0.0.tgz";
        sha1 = "a8479022eb1ac368a871389b635262c505ee368f";
      };
    };
    "strip-bom-3.0.0" = {
      name = "strip-bom";
      packageName = "strip-bom";
      version = "3.0.0";
      src = fetchurl {
        url = "https://registry.npmjs.org/strip-bom/-/strip-bom-3.0.0.tgz";
        sha1 = "2334c18e9c759f7bdd56fdef7e9ae3d588e68ed3";
      };
    };
    "strip-eof-1.0.0" = {
      name = "strip-eof";
      packageName = "strip-eof";
      version = "1.0.0";
      src = fetchurl {
        url = "https://registry.npmjs.org/strip-eof/-/strip-eof-1.0.0.tgz";
        sha1 = "bb43ff5598a6eb05d89b59fcd129c983313606bf";
      };
    };
    "supports-color-2.0.0" = {
      name = "supports-color";
      packageName = "supports-color";
      version = "2.0.0";
      src = fetchurl {
        url = "https://registry.npmjs.org/supports-color/-/supports-color-2.0.0.tgz";
        sha1 = "535d045ce6b6363fa40117084629995e9df324c7";
      };
    };
    "supports-color-5.4.0" = {
      name = "supports-color";
      packageName = "supports-color";
      version = "5.4.0";
      src = fetchurl {
        url = "https://registry.npmjs.org/supports-color/-/supports-color-5.4.0.tgz";
        sha512 = "3ks7qkl6s064qcdc5qnpzcwzcrnlzccz9m3faw54fnmsm2k8fzb9saqr5nhx7w9lnd4nbp0zg047zz8mwsd4fxfnalpb7kra619fdnf";
      };
    };
    "universalify-0.1.1" = {
      name = "universalify";
      packageName = "universalify";
      version = "0.1.1";
      src = fetchurl {
        url = "https://registry.npmjs.org/universalify/-/universalify-0.1.1.tgz";
        sha1 = "fa71badd4437af4c148841e3b3b165f9e9e590b7";
      };
    };
    "util-deprecate-1.0.2" = {
      name = "util-deprecate";
      packageName = "util-deprecate";
      version = "1.0.2";
      src = fetchurl {
        url = "https://registry.npmjs.org/util-deprecate/-/util-deprecate-1.0.2.tgz";
        sha1 = "450d4dc9fa70de732762fbd2d4a28981419a0ccf";
      };
    };
    "validate-npm-package-license-3.0.3" = {
      name = "validate-npm-package-license";
      packageName = "validate-npm-package-license";
      version = "3.0.3";
      src = fetchurl {
        url = "https://registry.npmjs.org/validate-npm-package-license/-/validate-npm-package-license-3.0.3.tgz";
        sha512 = "39caf21ga6s2gvpka90wdngdijarwmkix5fpgh9r94bw14fx1zfnf7j5mprgsdlh8dv0wpwxn65qn9gfwa8n3dxw3iqaj7qf994wxpb";
      };
    };
    "which-1.3.1" = {
      name = "which";
      packageName = "which";
      version = "1.3.1";
      src = fetchurl {
        url = "https://registry.npmjs.org/which/-/which-1.3.1.tgz";
        sha512 = "0hr4hxkk8yb9fz993bs69pf8z2z2qb6sdpxfxb84sd16lja9fsx444pk1ang1ivmjjv5srnsm6fihdj593w7rwxdh834cdmd9hms4hz";
      };
    };
    "which-module-2.0.0" = {
      name = "which-module";
      packageName = "which-module";
      version = "2.0.0";
      src = fetchurl {
        url = "https://registry.npmjs.org/which-module/-/which-module-2.0.0.tgz";
        sha1 = "d9ef07dce77b9902b8a3a8fa4b31c3e3f7e6e87a";
      };
    };
    "wrap-ansi-2.1.0" = {
      name = "wrap-ansi";
      packageName = "wrap-ansi";
      version = "2.1.0";
      src = fetchurl {
        url = "https://registry.npmjs.org/wrap-ansi/-/wrap-ansi-2.1.0.tgz";
        sha1 = "d8fc3d284dd05794fe84973caecdd1cf824fdd85";
      };
    };
    "wrappy-1.0.2" = {
      name = "wrappy";
      packageName = "wrappy";
      version = "1.0.2";
      src = fetchurl {
        url = "https://registry.npmjs.org/wrappy/-/wrappy-1.0.2.tgz";
        sha1 = "b5243d8f3ec1aa35f1364605bc0d1036e30ab69f";
      };
    };
    "y18n-3.2.1" = {
      name = "y18n";
      packageName = "y18n";
      version = "3.2.1";
      src = fetchurl {
        url = "https://registry.npmjs.org/y18n/-/y18n-3.2.1.tgz";
        sha1 = "6d15fba884c08679c0d77e88e7759e811e07fa41";
      };
    };
    "yallist-2.1.2" = {
      name = "yallist";
      packageName = "yallist";
      version = "2.1.2";
      src = fetchurl {
        url = "https://registry.npmjs.org/yallist/-/yallist-2.1.2.tgz";
        sha1 = "1c11f9218f076089a47dd512f93c6699a6a81d52";
      };
    };
    "yargs-8.0.2" = {
      name = "yargs";
      packageName = "yargs";
      version = "8.0.2";
      src = fetchurl {
        url = "https://registry.npmjs.org/yargs/-/yargs-8.0.2.tgz";
        sha1 = "6299a9055b1cefc969ff7e79c1d918dceb22c360";
      };
    };
    "yargs-parser-7.0.0" = {
      name = "yargs-parser";
      packageName = "yargs-parser";
      version = "7.0.0";
      src = fetchurl {
        url = "https://registry.npmjs.org/yargs-parser/-/yargs-parser-7.0.0.tgz";
        sha1 = "8d0ac42f16ea55debd332caf4c4038b3e3f5dfd9";
      };
    };
  };
in
{
  "postcss-cli-4.1.0" = nodeEnv.buildNodePackage {
    name = "postcss-cli";
    packageName = "postcss-cli";
    version = "4.1.0";
    src = fetchurl {
      url = "https://registry.npmjs.org/postcss-cli/-/postcss-cli-4.1.0.tgz";
      sha1 = "8f6803678acd7a4f21483f1a4039136f6e1c214f";
    };
    dependencies = [
      sources."ansi-regex-2.1.1"
      sources."ansi-styles-2.2.1"
      sources."anymatch-1.3.2"
      sources."argparse-1.0.10"
      sources."arr-diff-2.0.0"
      sources."arr-flatten-1.1.0"
      sources."array-union-1.0.2"
      sources."array-uniq-1.0.3"
      sources."array-unique-0.2.1"
      sources."async-each-1.0.1"
      sources."balanced-match-1.0.0"
      sources."binary-extensions-1.11.0"
      sources."brace-expansion-1.1.11"
      (sources."braces-1.8.5" // {
        dependencies = [
          sources."kind-of-6.0.2"
        ];
      })
      sources."builtin-modules-1.1.1"
      sources."camelcase-4.1.0"
      sources."chalk-1.1.3"
      sources."chokidar-1.7.0"
      sources."cli-cursor-2.1.0"
      sources."cli-spinners-1.3.1"
      (sources."cliui-3.2.0" // {
        dependencies = [
          sources."string-width-1.0.2"
        ];
      })
      sources."code-point-at-1.1.0"
      sources."color-convert-1.9.1"
      sources."color-name-1.1.3"
      sources."concat-map-0.0.1"
      sources."core-util-is-1.0.2"
      sources."cosmiconfig-2.2.2"
      sources."cross-spawn-5.1.0"
      sources."decamelize-1.2.0"
      sources."dependency-graph-0.5.2"
      sources."error-ex-1.3.1"
      sources."escape-string-regexp-1.0.5"
      sources."esprima-4.0.0"
      sources."execa-0.7.0"
      sources."expand-brackets-0.1.5"
      sources."expand-range-1.8.2"
      sources."extglob-0.3.2"
      sources."filename-regex-2.0.1"
      sources."fill-range-2.2.4"
      sources."find-up-2.1.0"
      sources."for-in-1.0.2"
      sources."for-own-0.1.5"
      sources."fs-extra-3.0.1"
      sources."fs.realpath-1.0.0"
      sources."fsevents-1.2.4"
      sources."get-caller-file-1.0.2"
      sources."get-stdin-5.0.1"
      sources."get-stream-3.0.0"
      sources."glob-7.1.2"
      sources."glob-base-0.3.0"
      sources."glob-parent-2.0.0"
      sources."globby-6.1.0"
      sources."graceful-fs-4.1.11"
      sources."has-ansi-2.0.0"
      sources."has-flag-3.0.0"
      sources."hosted-git-info-2.6.0"
      sources."inflight-1.0.6"
      sources."inherits-2.0.3"
      sources."invert-kv-1.0.0"
      sources."is-arrayish-0.2.1"
      sources."is-binary-path-1.0.1"
      sources."is-buffer-1.1.6"
      sources."is-builtin-module-1.0.0"
      sources."is-directory-0.3.1"
      sources."is-dotfile-1.0.3"
      sources."is-equal-shallow-0.1.3"
      sources."is-extendable-0.1.1"
      sources."is-extglob-1.0.0"
      sources."is-fullwidth-code-point-1.0.0"
      sources."is-glob-2.0.1"
      sources."is-number-2.1.0"
      sources."is-posix-bracket-0.1.1"
      sources."is-primitive-2.0.0"
      sources."is-stream-1.1.0"
      sources."isarray-1.0.0"
      sources."isexe-2.0.0"
      sources."isobject-2.1.0"
      sources."js-yaml-3.12.0"
      sources."jsonfile-3.0.1"
      sources."kind-of-3.2.2"
      sources."lcid-1.0.0"
      sources."load-json-file-2.0.0"
      sources."locate-path-2.0.0"
      sources."lodash-4.17.10"
      sources."log-symbols-2.2.0"
      sources."lru-cache-4.1.3"
      sources."math-random-1.0.1"
      sources."mem-1.1.0"
      sources."micromatch-2.3.11"
      sources."mimic-fn-1.2.0"
      sources."minimatch-3.0.4"
      sources."minimist-1.2.0"
      sources."nan-2.10.0"
      sources."normalize-package-data-2.4.0"
      sources."normalize-path-2.1.1"
      sources."npm-run-path-2.0.2"
      sources."number-is-nan-1.0.1"
      sources."object-assign-4.1.1"
      sources."object.omit-2.0.1"
      sources."once-1.4.0"
      sources."onetime-2.0.1"
      (sources."ora-1.4.0" // {
        dependencies = [
          sources."ansi-styles-3.2.1"
          sources."chalk-2.4.1"
          sources."supports-color-5.4.0"
        ];
      })
      sources."os-homedir-1.0.2"
      sources."os-locale-2.1.0"
      sources."p-finally-1.0.0"
      sources."p-limit-1.3.0"
      sources."p-locate-2.0.0"
      sources."p-try-1.0.0"
      sources."parse-glob-3.0.4"
      sources."parse-json-2.2.0"
      sources."path-exists-3.0.0"
      sources."path-is-absolute-1.0.1"
      sources."path-key-2.0.1"
      sources."path-type-2.0.0"
      sources."pify-2.3.0"
      sources."pinkie-2.0.4"
      sources."pinkie-promise-2.0.1"
      (sources."postcss-6.0.22" // {
        dependencies = [
          sources."ansi-styles-3.2.1"
          sources."chalk-2.4.1"
          sources."supports-color-5.4.0"
        ];
      })
      sources."postcss-load-config-1.2.0"
      sources."postcss-load-options-1.2.0"
      sources."postcss-load-plugins-2.3.0"
      (sources."postcss-reporter-4.0.0" // {
        dependencies = [
          sources."log-symbols-1.0.2"
        ];
      })
      sources."preserve-0.2.0"
      sources."process-nextick-args-2.0.0"
      sources."pseudomap-1.0.2"
      (sources."randomatic-3.0.0" // {
        dependencies = [
          sources."is-number-4.0.0"
        ];
      })
      sources."read-cache-1.0.0"
      sources."read-pkg-2.0.0"
      sources."read-pkg-up-2.0.0"
      sources."readable-stream-2.3.6"
      sources."readdirp-2.1.0"
      sources."regex-cache-0.4.4"
      sources."remove-trailing-separator-1.1.0"
      sources."repeat-element-1.1.2"
      sources."repeat-string-1.6.1"
      sources."require-directory-2.1.1"
      sources."require-from-string-1.2.1"
      sources."require-main-filename-1.0.1"
      sources."restore-cursor-2.0.0"
      sources."safe-buffer-5.1.2"
      sources."semver-5.5.0"
      sources."set-blocking-2.0.0"
      sources."set-immediate-shim-1.0.1"
      sources."shebang-command-1.2.0"
      sources."shebang-regex-1.0.0"
      sources."signal-exit-3.0.2"
      sources."source-map-0.6.1"
      sources."spdx-correct-3.0.0"
      sources."spdx-exceptions-2.1.0"
      sources."spdx-expression-parse-3.0.0"
      sources."spdx-license-ids-3.0.0"
      sources."sprintf-js-1.0.3"
      sources."string-width-2.1.1"
      sources."string_decoder-1.1.1"
      sources."strip-ansi-3.0.1"
      sources."strip-bom-3.0.0"
      sources."strip-eof-1.0.0"
      sources."supports-color-2.0.0"
      sources."universalify-0.1.1"
      sources."util-deprecate-1.0.2"
      sources."validate-npm-package-license-3.0.3"
      sources."which-1.3.1"
      sources."which-module-2.0.0"
      sources."wrap-ansi-2.1.0"
      sources."wrappy-1.0.2"
      sources."y18n-3.2.1"
      sources."yallist-2.1.2"
      (sources."yargs-8.0.2" // {
        dependencies = [
          sources."ansi-regex-3.0.0"
          sources."is-fullwidth-code-point-2.0.0"
          sources."strip-ansi-4.0.0"
        ];
      })
      sources."yargs-parser-7.0.0"
    ];
    buildInputs = globalBuildInputs;
    meta = {
      description = "CLI for PostCSS";
      homepage = "https://github.com/postcss/postcss-cli#readme";
      license = "MIT";
    };
    production = true;
    bypassCache = true;
  };
}